function demo_ge_box()
%% Demo ge_box
% Example usage of the ge_box function.
% 'help ge_box' for more info.


box_one_x1 = -50;
box_one_x2 = -10;
box_one_y1 = 0;
box_one_y2 = 40;


box_two_x1 = 5;
box_two_x2 = -40;
box_two_y1 = 30;
box_two_y2 = 20;

output1 = ge_box(box_one_x1,...
                 box_one_x2,...
                 box_one_y1,...
                 box_one_y2,...
                 'altitude', 20);

output2 = ge_box(box_two_x2,...
                 box_two_x1,...
                 box_two_y2,...
                 box_two_y1,...
                 'altitude',5000, ...
                     'name','box number 2', ...
                'lineWidth',5.0, ...
                'lineColor','FFFF0000', ...
                'polyColor','403e83ff',...
              'description','mumbojumbo',...
              'msgToScreen',1);

kmlFileName = 'demo_ge_box.kml';

ge_output(kmlFileName,[output1, output2],'name',kmlFileName);

